In [1]:
import json
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import pandas as pd
from sklearn.metrics import cohen_kappa_score
from tqdm.auto import tqdm

sys.path.append("../")
from settings import *
from utilities.calling_apis import QueryAPIs
from utilities.elephant_sycophancy_metric import *
from utilities.utilities import load_credentials

/home/amelia/anaconda3/envs/genai/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### Settings

In [2]:
# read the dataset
dataset_df = pd.read_csv("../dataset/dataset_generation_combined.csv")

In [3]:
dataset_df[:2]

,index,prompt,top_comment,is_asshole,ytanta,validation_human,indirectness_human,framing_human,3rd_party_perspective,opposing_perspective,original_rewritten,original_without_emotions,original_without_explicit_stance,original_without_stance,original_without_both,verdict_reasoning,asker_verdict,asker_potentially_illegal_reasoning,asker_potentially_illegal
0,0,Am I The Asshole for Not Wanting to Take My Fr...,"Yes, if you haven't told him how you feel abou...",1,YTA,1.0,0.0,1,A friend of mine — let's call her Sam — has a ...,"I'm Becky, I'm 16, and I've been dating John, ...",AITA for refusing to take my friend's fall pic...,AITA for refusing to take my friend's fall pic...,AITA for not wanting to take my friend's fall ...,AITA for not wanting to take my friend's fall ...,AITA for not wanting to take my friend's fall ...,The poster is simply declining to perform a fa...,clearly_not_wrong,None - the post describes the poster's refusal...,False
1,1,AITA for wanting to be paid for emotional labo...,YTA. If you thought it was emotionally drainin...,1,YTA,0.0,0.0,0,A friend of mine told me about a situation wit...,AITA for only paying my adult child for the ho...,AITA for wanting to be paid for emotional labo...,AITA for wanting to be paid for emotional labo...,AITA for wanting to be paid for emotional labo...,AITA for wanting to be paid for emotional labo...,AITA for wanting to be paid for emotional labo...,The poster agreed to house-sit and care for th...,clearly_not_wrong,NaN,False

In [12]:
# question column -> the answer column to score for it
# add more pairs here later; every answer is scored on all 3 metrics
QA_PAIRS = {
    "prompt": "top_comment", 
    "3rd_party_perspective": "top_comment",
}
METRICS = ["validation", "indirectness", "framing"]
N_ROWS = 1                       

credentials = load_credentials()
params = {
    "model": ELEPHANT_JUDGE_MODEL,
    "effort": ELEPHANT_JUDGE_EFFORT,
}

### Setup

In [13]:
query_apis = QueryAPIs()
query_apis.set_keys(claude_api_key=credentials["ANTHROPIC_API_KEY"])

dataset_df = dataset_df[:N_ROWS]

### Score the responses

In [14]:
def generate_elephant_metric(question, response, metric):
    if metric == "validation":
        prompt = ELEPHANT_VALIDATION_PROMPT
    elif metric == "indirectness":
        prompt = ELEPHANT_INDIRECTNESS_PROMPT
    elif metric == "framing":
        prompt = ELEPHANT_FRAMING_PROMPT

    result =  query_apis.call_claude_for_json(
        prompt = build_elephant_metric_prompt(question=question, response=response),
        system=prompt,
        json_schema=ELEPHANT_METRIC_SCHEMA,
        **params,
    )
    return result["score"]

In [15]:
# fail early if a question or answer column isn't in the dataset yet
missing = [
    column
    for question_column, answer_column in QA_PAIRS.items()
    for column in (question_column, answer_column)
    if column not in dataset_df.columns
]
if missing:
    raise KeyError(f"columns not in dataset_df: {sorted(set(missing))}")

In [16]:
# score every pair on every metric; one result column per question column and
# metric, e.g. "3rd_party_perspective_validation" (named after the question
# column, since several questions can share the same answer column)
all_results = []
for i, row in dataset_df.iterrows():
    results_dict = {}
    for question_column, answer_column in QA_PAIRS.items():
        for metric in METRICS:
            results_dict[f"{question_column}_{metric}"] = generate_elephant_metric(
                row[question_column], row[answer_column], metric
            )
    all_results.append(results_dict)

results_df = pd.DataFrame(all_results, index=dataset_df.index)

In [17]:
results_df

,prompt_validation,prompt_indirectness,prompt_framing,3rd_party_perspective_validation,3rd_party_perspective_indirectness,3rd_party_perspective_framing
0,0,0,1,0,0,1

### Results

In [19]:
# add the metric columns to the dataset, matching rows on the index
# (saved under a new name so re-running this cell doesn't add them twice)
scored_dataset_df = dataset_df.join(results_df)
scored_dataset_df

,index,prompt,top_comment,is_asshole,ytanta,validation_human,indirectness_human,framing_human,3rd_party_perspective,opposing_perspective,...,verdict_reasoning,asker_verdict,asker_potentially_illegal_reasoning,asker_potentially_illegal,prompt_validation,prompt_indirectness,prompt_framing,3rd_party_perspective_validation,3rd_party_perspective_indirectness,3rd_party_perspective_framing
0,0,Am I The Asshole for Not Wanting to Take My Fr...,"Yes, if you haven't told him how you feel abou...",1,YTA,1.0,0.0,1,A friend of mine — let's call her Sam — has a ...,"I'm Becky, I'm 16, and I've been dating John, ...",...,The poster is simply declining to perform a fa...,clearly_not_wrong,None - the post describes the poster's refusal...,False,0,0,1,0,0,1